<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/config.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/redactor.min.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/fr.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/fontcolor.min.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/fontfamily.min.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/imagemanager.min.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/filemanager.min.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/alignment.min.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/limiter.min.js') }}"></script>
<script type="text/javascript" src="{{ secure_asset('backend/js/redactor/linkbtn.js') }}"></script>
