<?php
use Illuminate\Database\Seeder;

class ContentSeeder extends Seeder
{
    public function run()
    {
        \DB::table('contents')->truncate();

        $contents = array(
            array('id' => '1','title' => '','content' => '<p>Anonyma accumsan étiam himenaéos fusce laçus cél cras nam inceptos auctor, dès faucibus aliquàm ïn nec curabitur blandit. Tellus felis class nostré libéro pulvîar tùrpus anonyma iaculisé blandit facîlisis curae, cél at ultrûcéas faucibus risius blandît egestas duis tristiqué odio vivamus, vitae ultricités Frînglilia nisi cràs dapibus sit condimentûm rûtrum habitasse, ullamcorpér duis ùrci curae fancibüs arcu. </p>','image' => '','url' => '','style' => NULL,'rang' => '0','page_id' => '1','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-08 17:56:47','updated_at' => '2016-01-08 17:56:47','deleted_at' => NULL),
            array('id' => '2','title' => 'Le droit pour le praiticen 2014/2015','content' => 'Ipsum iaculisé susîcpit pérès à enim l\'sempér faucibus aliquét voluptà at diam ïpsum alèquam, susîcpit lectus etiam euismod viverra interdum varius malesuada lacinia convallis aliquàm aliquet, odio curabitur ôdiot sed nulla nisi niçl mollis dès dès porta interdùm vivamus vel, ac auctor m\'. Gravida ultricités vitae phasellus tristiqué quisquées métus éros, interdum ut primis aliquam tempor nostra, quisque séllicitudén dui suspendisse risius habitasse mollis. ','image' => '','url' => '','style' => NULL,'rang' => '0','page_id' => '1','categorie_id' => NULL,'type' => 'lien','created_at' => '2016-01-08 17:58:00','updated_at' => '2016-01-08 17:58:00','deleted_at' => NULL),
            array('id' => '3','title' => 'Genève','content' => '<p style="text-align: center;"><a href="http://ge.ch/justice/commission-de-conciliation-en-matiere-de-baux-et-loyers" target="_blank" class="external-link-new-window">Autorité cantonale de conciliation</a><br><a href="https://ge.ch/justice/tribunal-des-baux-et-loyers" target="_blank" class="external-link-new-window">Tribunaux</a></p>','image' => 'files/uploads/0ca9bf9491.png','url' => '','style' => NULL,'rang' => '0','page_id' => '1','categorie_id' => NULL,'type' => 'autorite','created_at' => '2016-01-09 10:52:58','updated_at' => '2016-01-09 10:52:58','deleted_at' => NULL),
            array('id' => '4','title' => 'Présentation','content' => '<p>Plate-forme internet du Séminaire sur le droit du bail de 
l’Université de Neuchâtel, bail.ch propose une importante base de 
données consacrée au droit du bail.</p><p>Il présente les activités du Séminaire et offre divers outils 
pratiques et scientifiques utiles aux bailleurs et locataires ainsi 
qu\'aux spécialistes du domaine.</p>','image' => '','url' => '','style' => NULL,'rang' => '0','page_id' => '2','categorie_id' => NULL,'type' => 'text','created_at' => '2016-02-03 08:27:31','updated_at' => '2016-02-03 08:27:31','deleted_at' => NULL),
            array('id' => '6','title' => 'Le Séminaire sur le droit du bail','content' => '<p>Le Séminaire sur le droit du bail de l’Université de Neuchâtel a été 
créé en 1980. La direction actuelle  est composée des professeurs 
				François Bohnet et Blaise Carron et de Me Philippe Conod, chargé 
d\'un enseignement spécialisé en droit du bail à la faculté de droit. 
Elle est 
				entourée du professeur honoraire Pierre Wessner, de Me Marino 
Montini, collaborateur scientifique, de Mme Patricia Dietschy, docteure 
en droit, 
				de M. Julien Broquet, assistant-doctorant, et de Mme Sylvia Staehli,
 secrétaire.</p>','image' => '','url' => '','style' => NULL,'rang' => '0','page_id' => '2','categorie_id' => NULL,'type' => 'text','created_at' => '2016-01-16 17:58:40','updated_at' => '2016-01-16 17:58:40','deleted_at' => NULL),
            array('id' => '7','title' => 'Les activités du Séminaire','content' => '<p>Le Séminaire sur le droit du bail propose tous les deux ans des 
conférences pour les spécialistes du domaine, publie annuellement 
				la Revue du droit du bail et mensuellement une Newsletter online. Il
 a édité en 2010 un Commentaire sur le droit du bail, aux éditions 
				Helbing Lichtenhahn.</p><p>Le Séminaire finance un enseignement de droit du bail à la 
faculté de droit de l\'Université de Neuchâtel, confié à Me Philippe 
Conod. 
				Ce cours est intégré au Master de droit social.</p>','image' => '','url' => '','style' => NULL,'rang' => '0','page_id' => '2','categorie_id' => NULL,'type' => 'text','created_at' => '2016-01-16 17:59:02','updated_at' => '2016-01-16 17:59:02','deleted_at' => NULL),
            array('id' => '8','title' => '17e Séminaire sur le droit du bail','content' => '<p><strong>L\'ouvrage</strong> recueillant les interventions du <strong>17e Séminaire sur le droit du bail</strong> peut être commandé en ligne, 
					<a href="http://pubdroit.local/bail/" target="_blank" class="external-link-new-window">en cliquant ici</a>.</p><p>Les <strong>présentations</strong> de ces journées peuvent être téléchargées 
					<a href="http://pubdroit.local/bail/" target="_blank" class="external-link-new-window">en cliquant ici</a>.</p><p>Toutes les précédentes publications du Séminaire sur le droit du
 bail se trouvent également sur notre site publications-droit.ch, 
					<a href="http://pubdroit.local/bail/" target="_blank" class="external-link-new-window">collection bail</a>.</p><p><strong>Le 18e Séminaire aura lieu</strong> en deux éditions identiques :<br>vendredi <strong>3 &amp;</strong> samedi <strong>4 octobre 2014</strong> 
					(1ère édition)<br>vendredi <strong>17 &amp;</strong> samedi <strong>18 octobre 2014</strong> (2e édition)</p>','image' => '','url' => '','style' => 'agenda','rang' => '0','page_id' => '2','categorie_id' => NULL,'type' => 'text','created_at' => '2016-02-03 08:27:07','updated_at' => '2016-02-03 08:27:07','deleted_at' => NULL),
            array('id' => '9','title' => '','content' => '<p><strong>Loi fédérale du 30 mars 1911</strong> complétant le code civil suisse (Livre cinquième: Droit des obligations) autrement dit: Code des obligations (CO) (<a href="http://www.admin.ch/ch/f/rs/c220.html" target="_blank" class="external-link-new-window">RS 220</a>) voir notamment la partie générale et, surtout, la 2e partie, titre VIIIe, art. 253-304 (bail à loyer, bail à ferme).</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 14:41:46','updated_at' => '2016-01-17 14:41:46','deleted_at' => NULL),
            array('id' => '10','title' => '','content' => '<p><strong>Ordonnance du 9 mai 1990</strong> sur le bail à loyer et le bail à ferme d\'habitations et de locaux commerciaux (OBLF) (<a href="http://www.admin.ch/ch/f/rs/c221_213_11.html" target="_blank" class="external-link-new-window">RS 221.213.11</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:09:03','updated_at' => '2016-01-17 13:09:03','deleted_at' => NULL),
            array('id' => '11','title' => '','content' => '<p><strong>Ordonnance du DFE du 22 janvier 2008</strong> sur l\'établissement du taux hypothécaire moyen déterminant pour la fixation des loyers (Ordonnance sur le taux hypothécaire) (<a href="http://www.admin.ch/ch/f/rs/c221_213_111.html" target="_blank" class="external-link-new-window">RS 221.213.111</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:09:12','updated_at' => '2016-01-17 13:09:12','deleted_at' => NULL),
            array('id' => '12','title' => '','content' => '<p><strong>Loi fédérale du 23 juin 1995</strong> sur les contrats-cadres de baux à loyer et leur déclaration de force obligatoire générale (<a href="http://www.admin.ch/ch/f/rs/c221_213_15.html" target="_blank" class="external-link-new-window">RS 221.213.15</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:09:26','updated_at' => '2016-01-17 13:09:26','deleted_at' => NULL),
            array('id' => '13','title' => '','content' => '<p><strong>Ordonnance du 31 janvier 1996</strong> sur les contrats-cadres de baux à loyer et leur déclaration de force obligatoire générale (OCBD) (<a href="http://www.admin.ch/ch/f/rs/c221_213_151.html" target="_blank" class="external-link-new-window">RS 221.213.151</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:09:35','updated_at' => '2016-01-17 13:09:35','deleted_at' => NULL),
            array('id' => '14','title' => '','content' => '<p><a href="http://www.bwo.admin.ch/dokumentation/00179/00277/index.html?lang=fr" target="_blank" class="external-link-new-window">Contrat-cadre romand de baux à loyer</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:09:44','updated_at' => '2016-01-17 13:09:44','deleted_at' => NULL),
            array('id' => '15','title' => '','content' => '<p><strong>Loi fédérale du 4 octobre 1985</strong> sur le bail à ferme agricole (LBFA) (<a href="http://www.admin.ch/ch/f/rs/c221_213_2.html" target="_blank" class="external-link-new-window">RS 221.213.2</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:09:54','updated_at' => '2016-01-17 13:09:54','deleted_at' => NULL),
            array('id' => '16','title' => '','content' => '<p><strong>Ordonnance du 11 février 1987</strong> concernant le calcul des fermages agricoles (O sur les fermages) (<a href="http://www.admin.ch/ch/f/rs/c221_213_221.html" target="_blank" class="external-link-new-window">RS 221.213.221</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:25:08','updated_at' => '2016-01-17 13:25:08','deleted_at' => NULL),
            array('id' => '17','title' => '','content' => '<p><strong>Loi fédérale du 21 mars 2003</strong> encourageant le logement à loyer ou à prix modérés (Loi sur le logement, LOG) (<a href="http://www.admin.ch/ch/f/rs/c842.html" target="_blank" class="external-link-new-window">RS 842</a>) Ordonnance encourageant le logement à loyer ou à prix modérés (Ordonnance sur le logement, OLOG) (<a href="http://www.admin.ch/ch/f/rs/c842_1.html" target="_blank" class="external-link-new-window">RS 842.1</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:25:17','updated_at' => '2016-01-17 13:25:17','deleted_at' => NULL),
            array('id' => '18','title' => '','content' => '<p><strong>Loi fédérale du 4 octobre 1974</strong> encourageant la construction et l\'accession à la propriété de logements (LCAP) (<a href="http://www.admin.ch/ch/f/rs/c843.html" target="_blank" class="external-link-new-window">RS 843</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:25:24','updated_at' => '2016-01-17 13:25:24','deleted_at' => NULL),
            array('id' => '19','title' => '','content' => '<p><strong>Ordonnance du 30 novembre 1981</strong> relative à la loi fédérale  encourageant la construction et l\'accession à la propriété de logements  (OLCAP) (<a href="http://www.admin.ch/ch/f/rs/c843_1.html" target="_blank" class="external-link-new-window">RS 843.1</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:25:33','updated_at' => '2016-01-17 13:25:33','deleted_at' => NULL),
            array('id' => '20','title' => '','content' => '<p><strong>Ordonnance du 24 septembre 1993</strong> relative aux limites de revenu  et de fortune pour les abaissements supplémentaires relatifs à la  construction de logements (<a href="http://www.admin.ch/ch/f/rs/c843_123_3.html" target="_blank" class="external-link-new-window">RS 843.123.3</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:25:40','updated_at' => '2016-01-17 13:25:40','deleted_at' => NULL),
            array('id' => '21','title' => '','content' => '<p><strong>Ordonnance du 29 décembre 1997</strong> concernant le coût de construction des nouveaux logements (<a href="http://www.admin.ch/ch/f/rs/c843_143_1.html" target="_blank" class="external-link-new-window">RS 843.143.1</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:25:47','updated_at' => '2016-01-17 13:25:47','deleted_at' => NULL),
            array('id' => '22','title' => '','content' => '<p><strong>Loi fédérale du 20 mars 1970</strong> concernant l\'amélioration du logement dans les régions de montagne (LALM) (<a href="http://www.admin.ch/ch/f/rs/c844.html" target="_blank" class="external-link-new-window">RS 844</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:25:57','updated_at' => '2016-01-17 13:25:57','deleted_at' => NULL),
            array('id' => '23','title' => '','content' => '<p><strong>Ordonnance du 17 avril 1991</strong> concernant l\'amélioration du logement dans les régions de montagne (<a href="http://www.admin.ch/ch/f/rs/c844_1.html" target="_blank" class="external-link-new-window">RS 844.1</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:26:15','updated_at' => '2016-01-17 13:26:15','deleted_at' => NULL),
            array('id' => '24','title' => '','content' => '<p><strong>Ordonnance du 24 septembre 1993</strong> sur les limites de revenu et de  fortune dans le cadre de l\'amélioration du logement dans les régions de  montagne (<a href="http://www.admin.ch/ch/f/rs/c844_12.html" target="_blank" class="external-link-new-window">RS 844.12</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:26:23','updated_at' => '2016-01-17 13:26:23','deleted_at' => NULL),
            array('id' => '25','title' => '','content' => '<p><strong>Code de procédure civile du 19 décembre 2008</strong> (CPC) (<a href="http://www.admin.ch/ch/f/rs/c272.html" target="_blank" class="external-link-new-window">RS 272</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:26:31','updated_at' => '2016-01-17 13:26:31','deleted_at' => NULL),
            array('id' => '26','title' => '','content' => '<p><strong>Loi fédérale sur la poursuite pour dettes et la faillite du 11 avril 1889</strong> (<a href="http://www.admin.ch/ch/f/rs/c281_1.html" target="_blank" class="external-link-new-window">RS 281.1</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:26:39','updated_at' => '2016-01-17 13:26:39','deleted_at' => NULL),
            array('id' => '27','title' => '','content' => '<p><strong>Loi fédérale sur le Tribunal fédéral du 17 juin 2005</strong> (LTF) (<a href="http://www.admin.ch/ch/f/rs/c173_110.html" target="_blank" class="external-link-new-window">RS 173.110</a>)</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 13:26:46','updated_at' => '2016-01-17 13:26:46','deleted_at' => NULL),
            array('id' => '28','title' => 'Neuchâtel','content' => '<p style="text-align: center;"><a href="http://www.ne.ch/autorites/PJNE/tribunaux-regionaux/Pages/INST-conc.aspx" target="_blank" class="external-link-new-window">Autorités de conciliation </a><br><a href="http://www.ne.ch/autorites/PJNE/tribunaux-regionaux/Pages/INST-civ.aspx" target="_blank" class="external-link-new-window">Tribunaux</a></p>','image' => 'files/uploads/45fe078900.png','url' => '','style' => '','rang' => '0','page_id' => '4','categorie_id' => NULL,'type' => 'autorite','created_at' => '2016-01-17 13:34:17','updated_at' => '2016-01-17 13:34:17','deleted_at' => NULL),
            array('id' => '29','title' => 'Vaud','content' => '<p><a href="http://www.vd.ch/themes/territoire/districts-prefectures/commissions-prefectorales-de-conciliation/" target="_blank" class="external-link-new-window">Autorités de conciliation (Préfectures)</a><br><a href="http://www.vd.ch/autorites/ordre-judiciaire/tribunal-des-baux/" target="_blank" class="external-link-new-window">Tribunaux</a></p>','image' => 'files/uploads/45fe078900.png','url' => '','style' => '','rang' => '0','page_id' => '4','categorie_id' => NULL,'type' => 'autorite','created_at' => '2016-01-17 13:40:14','updated_at' => '2016-01-17 13:40:14','deleted_at' => NULL),
            array('id' => '30','title' => 'Genève','content' => '<p><a href="http://ge.ch/justice/commission-de-conciliation-en-matiere-de-baux-et-loyers" target="_blank" class="external-link-new-window">Autorité cantonale de conciliation</a><br><a href="https://ge.ch/justice/tribunal-des-baux-et-loyers" target="_blank" class="external-link-new-window">Tribunaux</a></p>','image' => 'files/uploads/0ca9bf9491.png','url' => '','style' => '','rang' => '0','page_id' => '4','categorie_id' => NULL,'type' => 'autorite','created_at' => '2016-01-17 13:40:38','updated_at' => '2016-01-17 13:40:38','deleted_at' => NULL),
            array('id' => '31','title' => 'Jura','content' => '<p><a href="http://www.jura.ch/JUST/Renseignements-juridiques/Droit-du-travail-et-du-bail.html" target="_blank" class="external-link-new-window">Autorités de conciliation (JU)</a><br><a href="http://www.jura.ch/JUST/Instances-judiciaires/Tribunal-de-premiere-instance/Tribunal-des-baux-a-loyer-et-a-ferme.html" target="_blank" class="external-link-new-window">Tribunaux (JU)</a></p>','image' => 'files/uploads/58b66c6d5e.png','url' => '','style' => '','rang' => '0','page_id' => '4','categorie_id' => NULL,'type' => 'autorite','created_at' => '2016-01-17 13:41:06','updated_at' => '2016-01-17 13:41:06','deleted_at' => NULL),
            array('id' => '33','title' => 'Fribourg','content' => '<p><a href="http://www.fr.ch/pj/fr/pub/juridictions/organisation/bail.htm" target="_blank" class="external-link-new-window">Autorités de conciliation</a><br><a href="http://www.fr.ch/pj/fr/pub/juridictions/organisation/bail.htm" target="_blank" class="external-link-new-window">Tribunaux</a></p>','image' => 'files/uploads/dfeb018409.png','url' => '','style' => '','rang' => '0','page_id' => '4','categorie_id' => NULL,'type' => 'autorite','created_at' => '2016-01-17 13:42:41','updated_at' => '2016-01-17 13:42:41','deleted_at' => NULL),
            array('id' => '34','title' => 'Valais','content' => '<p><a href="https://www.vs.ch/Navig/navig.asp?MenuID=21513&amp;Language=fr" target="_blank" class="external-link-new-window">Autorité cantonale de conciliation</a><br><a href="http://www.vs.ch/Navig/navig.asp?MenuID=25137" target="_blank" class="external-link-new-window">Tribunaux</a></p>','image' => 'files/uploads/8aa7ed959b.png','url' => '','style' => '','rang' => '0','page_id' => '4','categorie_id' => NULL,'type' => 'autorite','created_at' => '2016-01-17 13:43:03','updated_at' => '2016-01-17 13:43:03','deleted_at' => NULL),
            array('id' => '35','title' => 'Berne','content' => '<p><a href="http://www.justice.be.ch/justice/fr/index/justiz/organisation/obergericht/ueber_uns/schlichtungsbehoerden.html" target="_blank" class="external-link-new-window">Autorités de conciliation (BE)</a><br><a href="http://www.justice.be.ch/justice/fr/index/justiz/organisation/obergericht/ueber_uns/regionalgerichte.html" target="_blank" class="external-link-new-window">Tribunaux (BE)</a></p>','image' => 'files/uploads/1a3d0e3117.png','url' => '','style' => '','rang' => '0','page_id' => '4','categorie_id' => NULL,'type' => 'autorite','created_at' => '2016-01-17 13:43:21','updated_at' => '2016-01-17 13:43:21','deleted_at' => NULL),
            array('id' => '39','title' => '','content' => '<p>test<br></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 14:57:27','updated_at' => '2016-01-17 14:57:27','deleted_at' => '2016-01-17 14:57:27'),
            array('id' => '40','title' => '','content' => '<p>test</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 14:58:07','updated_at' => '2016-01-17 14:58:07','deleted_at' => '2016-01-17 14:58:07'),
            array('id' => '41','title' => '','content' => '<p>test</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 14:58:40','updated_at' => '2016-01-17 14:58:40','deleted_at' => '2016-01-17 14:58:40'),
            array('id' => '42','title' => '','content' => '<p>test</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '3','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-01-17 14:59:48','updated_at' => '2016-01-17 14:59:48','deleted_at' => '2016-01-17 14:59:48'),
            array('id' => '43','title' => 'Etat','content' => '<p><a href="http://www.bwo.admin.ch/" target="_blank" class="external-link-new-window">Office fédéral du logement (OFL)</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '5','categorie_id' => NULL,'type' => 'lien','created_at' => '2016-01-17 15:30:04','updated_at' => '2016-01-17 15:30:04','deleted_at' => NULL),
            array('id' => '44','title' => 'Associations','content' => '<p><a href="http://www.asloca.ch/" target="_blank" class="external-link-new-window">Association suisse des locataires (ASLOCA) </a><br><a href="http://www.mieterverband.ch/" target="_blank" class="external-link-new-window">Mieterinnen- und Mieterverband Deutschschweiz</a><br><a href="http://www.asi-infoalloggio.ch/" target="_blank" class="external-link-new-window">Associazione Svizzera Inquilini</a>
</p><p><i>à noter que sa section vaudoise a créé une banque de données payante de </i><a href="http://www.fichesjuridiques-asloca.ch/" target="_blank" class="external-link-new-window"><i>fiches juridiques</i></a>
</p><p><a href="http://www.catef.ch/" target="_blank" class="external-link-new-window">Camera Ticinese dell\' Economia Fondiaria (CATEF)</a><br><a href="http://www.fri.ch/" target="_blank" class="external-link-new-window">Fédération romande immobilière (FRI)</a><br><a href="http://www.hev-schweiz.ch/" target="_blank" class="external-link-new-window">Hauseigentümerverband (HEV)</a><br><a href="http://www.svit.ch/fr/svit-romandie.html" target="_blank" class="external-link-new-window">Association suisse de l\'économie immobilière (SVIT Romandie)</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '5','categorie_id' => NULL,'type' => 'lien','created_at' => '2016-01-17 15:30:22','updated_at' => '2016-01-17 15:30:22','deleted_at' => NULL),
            array('id' => '45','title' => 'Revues suisses concernant le droit du bail','content' => '<p><a href="http://www.mietrecht.ch/index.php" target="_blank" class="external-link-new-window">Mietrechtspraxis (mp)</a> consultable également via <a href="http://www.swisslex.ch" target="_blank" class="external-link-new-window">Swisslex</a><br><a href="http://www.svit.ch/svit-schweiz/publikationen/mietrecht-aktuell.html" target="_blank" class="external-link-new-window">Mietrecht Aktuell (mra)</a> consultable également via <a href="http://www.swisslex.ch/" target="_blank" class="external-link-new-window">Swisslex</a><br><a href="http://www.gerichte-zh.ch/themen/miete/hilfen/zuercher-mietrechtspraxis.html" target="_blank" class="external-link-new-window">Zürcher Mietrechtspraxis (zmp)</a><br><a href="http://www.bwo.admin.ch/dokumentation/00106/00110/index.html?lang=fr" target="_blank" class="external-link-new-window">Communications de l\'Office fédéral du logement</a><br><a href="http://www.cvi.ch/pulications-formules/guides.html" target="_blank" class="external-link-new-window">Cahiers du bail</a><br><a href="http://www.asloca.ch/journal-de-lasloca" target="_blank" class="external-link-new-window">Droit au logement</a> voir aussi ses <a href="http://www.fichesjuridiques-asloca.ch/" target="_blank" class="external-link-new-window">fiches juridiques en ligne</a><br><a href="http://www.bail.ch/index.php?id=97" class="internal-link">Droit du bail</a> consultable également via <a href="http://www.swisslex.ch/" target="_blank" class="external-link-new-window">Swisslex</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '5','categorie_id' => NULL,'type' => 'lien','created_at' => '2016-01-17 15:30:40','updated_at' => '2016-01-17 15:30:40','deleted_at' => NULL),
            array('id' => '46','title' => 'Revues suisses pouvant contenir des articles intéressants pour le droit du bail','content' => '<p><a href="http://www.fri.ch/fr/revue-propriete-et-publications/" target="_blank" class="external-link-new-window">Propriété</a><br><a href="http://www.bonasavoir.ch/" target="_blank" class="external-link-new-window">Bon à savoir</a><br><a href="http://www.frc.ch/" target="_blank" class="external-link-new-window">J\'achète mieux</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '5','categorie_id' => NULL,'type' => 'lien','created_at' => '2016-01-17 15:30:56','updated_at' => '2016-01-17 15:30:56','deleted_at' => NULL),
            array('id' => '47','title' => 'Formulaire d’inscription','content' => '<p><strong>Le locataire est-il lié lorsqu\'il signe un simple formulaire d\'inscription ?</strong></p><p>Non,
 le locataire qui remplit un tel formulaire ne formule pas une offre 
mais un simple appel d’offre et ne s’engage pas à conclure le contrat en
 cas de réponse positive du bailleur.</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '6','categorie_id' => NULL,'type' => 'faq','created_at' => '2016-01-24 08:06:46','updated_at' => '2016-01-24 08:06:46','deleted_at' => '2016-01-24 08:06:46'),
            array('id' => '48','title' => 'Mariage mixte conclu à l\'étranger','content' => '<p>Conditions de la délivrance d’un certificat de capacité matrimoniale.
 Fanny Matthey vous propose une analyse de l’arrêt du Tribunal fédéral 
5A_107/2016 du 9 août 2016.
</p>

<p><a href="http://www.droitmatrimonial.ch/index.php?id=206&uid=499">En savoir plus</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '10','categorie_id' => NULL,'type' => 'text','created_at' => '2016-11-02 16:33:20','updated_at' => '2016-11-02 16:33:20','deleted_at' => NULL),
            array('id' => '49','title' => 'L’autorité parentale conjointe et le droit de déterminer le lieu de résidence de l’enfant','content' => '<p>Magalie Wyssen et Sabrina Burgat se sont penchées sur cette question 
et vous proposent une analyse de l\'arrêt du Tribunal fédéral 5A_945/2015
 du 7 juillet 2016.
</p>

<p><a href="http://www.droitmatrimonial.ch/index.php?id=206&uid=495">En savoir plus</a>
</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '10','categorie_id' => NULL,'type' => 'text','created_at' => '2016-11-02 16:33:58','updated_at' => '2016-11-02 16:33:58','deleted_at' => NULL),
            array('id' => '50','title' => 'Modification d’une convention entre époux en mesures protectrices et provisionnelles : cherchez l’erreur !','content' => '<p>Céline de Weck-Immelé vous propose une analyse de l’arrêt du Tribunal fédéral 5A_842/2015 du 26 mai 2016.
</p>

<p><a href="http://www.droitmatrimonial.ch/index.php?id=206&uid=491">En savoir plus</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '10','categorie_id' => NULL,'type' => 'text','created_at' => '2016-11-02 16:34:23','updated_at' => '2016-11-02 16:34:23','deleted_at' => NULL),
            array('id' => '51','title' => 'BIENVENUE sur publications-droit.ch','content' => '<p>Dapibus ante accumasa laoreet mauris nostra torquenté blandît néc lobortis duèis, ùrci fringilla taciti senectus malésdum félis morbié suscipit dictumst métus, çunc himenaéos namé primis ultrûcéas anonyma lilitoxic cras dictum. Nombre phaséllœs nîbh fuscé Frînglilia égét eu sit in quam lobortïs phasellus pellentecipit alèquam. Lorem ad quîs j\'libéro pharétra vivamus mollis ultricités ut, vulputaté ac pulvinar èst co</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '24','categorie_id' => NULL,'type' => 'text','created_at' => '2016-12-12 15:21:18','updated_at' => '2016-12-12 15:21:18','deleted_at' => NULL),
            array('id' => '52','title' => '','content' => '<p>uoikuztrewqrtzuikl</p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '24','categorie_id' => NULL,'type' => 'loi','created_at' => '2016-12-12 15:21:35','updated_at' => '2016-12-12 15:21:35','deleted_at' => NULL),
            array('id' => '53','title' => '','content' => '<p><a href="http://www.bail.ch/fileadmin/media/pdf/bibliographie/1_Ouvrages_generaux.pdf" target="_blank" class="download">1. Ouvrages généraux</a></p>','image' => 'files/pictos/bail/base.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 13:32:08','updated_at' => '2017-02-06 13:48:30','deleted_at' => '2017-02-06 13:48:30'),
            array('id' => '54','title' => '','content' => '<p><a href="http://shop.local/files/uploads/1_Ouvrages_generaux.pdf">1_Ouvrages_generaux.pdf</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 13:48:14','updated_at' => '2017-02-06 13:48:23','deleted_at' => '2017-02-06 13:48:23'),
            array('id' => '55','title' => '','content' => '<p><a href="http://shop.local/files/uploads/1_Ouvrages_generaux.pdf">1. Ouvrages généraux</a></p>','image' => 'files/pictos/bail/base.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 13:49:16','updated_at' => '2017-02-06 14:06:12','deleted_at' => '2017-02-06 14:06:12'),
            array('id' => '56','title' => '','content' => '<a href="http://shop.local/files/uploads/2_Dispositions_generales_01.pdf">2. Dispositions générales</a>','image' => 'files/pictos/bail/base.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 14:03:56','updated_at' => '2017-02-06 14:06:06','deleted_at' => '2017-02-06 14:06:06'),
            array('id' => '57','title' => '','content' => '<p><a href="http://shop.local/files/uploads/1_Ouvrages_generaux.pdf"></a></p><p><img src="http://shop.local/files/uploads/03597261d9.jpeg" "=""></p><p><a href="http://shop.local/files/uploads/1_Ouvrages_generaux.pdf">1. Ouvrages généraux</a><a href="http://www.bail.ch/fileadmin/media/pdf/bibliographie/1_Ouvrages_generaux.pdf" target="_blank" class="download"></a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'loi','created_at' => '2017-02-06 14:06:41','updated_at' => '2017-02-06 14:16:33','deleted_at' => '2017-02-06 14:16:33'),
            array('id' => '58','title' => '','content' => '<p><img src="http://shop.local/files/uploads/03597261d9.jpeg"></p><p><a href="http://shop.local/files/uploads/2_Dispositions_generales_01.pdf">2 Dispositions_generales</a></p>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'loi','created_at' => '2017-02-06 14:14:06','updated_at' => '2017-02-06 14:16:28','deleted_at' => '2017-02-06 14:16:28'),
            array('id' => '59','title' => '','content' => '<a href="http://shop.local/files/uploads/3_Protection_contre_les_loyers_abusifs_01.pdf"><img src="http://shop.local/files/uploads/04c5586b88.jpeg" "=""></a><a href="http://shop.local/files/uploads/3_Protection_contre_les_loyers_abusifs_01.pdf">3. Protection contre les loyers abusifs</a><br>','image' => '','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'loi','created_at' => '2017-02-06 14:15:42','updated_at' => '2017-02-06 14:16:22','deleted_at' => '2017-02-06 14:16:22'),
            array('id' => '60','title' => '','content' => '<p><a href="http://shop.local/files/uploads/1_Ouvrages_generaux.pdf">1. Ouvrages généraux</a></p>','image' => 'files/pictos/bail/base.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 14:29:37','updated_at' => '2017-02-06 14:29:37','deleted_at' => NULL),
            array('id' => '61','title' => '','content' => '<p><a href="http://shop.local/files/uploads/2_Dispositions_generales_01.pdf">2. Dispositions générales</a></p>','image' => 'files/pictos/bail/base.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 14:30:06','updated_at' => '2017-02-06 14:30:06','deleted_at' => NULL),
            array('id' => '62','title' => '','content' => '<a href="http://shop.local/files/uploads/3_Protection_contre_les_loyers_abusifs.pdf">3. Protection contre les loyers abusifs</a>','image' => 'files/pictos/bail/04c5586b88.jpeg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 14:30:49','updated_at' => '2017-02-06 14:30:49','deleted_at' => NULL),
            array('id' => '63','title' => '','content' => '<p><a href="http://shop.local/files/uploads/4_Protection_contre_les_conges_01.pdf">4. Protection contre les congés</a></p>','image' => 'files/pictos/bail/conge.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 14:31:24','updated_at' => '2017-02-06 14:31:24','deleted_at' => NULL),
            array('id' => '64','title' => '','content' => '<a href="http://shop.local/files/uploads/5_Autorites_et_procedure_01.pdf">5. Autorités et procédure</a>','image' => 'files/pictos/bail/procedure.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 14:31:56','updated_at' => '2017-02-06 14:31:56','deleted_at' => NULL),
            array('id' => '65','title' => '','content' => '<p><a href="http://shop.local/files/uploads/6_Bail_a_ferme_01.pdf">6. Bail à ferme</a></p>','image' => 'files/pictos/bail/ferme.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 14:32:21','updated_at' => '2017-02-06 14:32:21','deleted_at' => NULL),
            array('id' => '66','title' => '','content' => '<p><a href="http://shop.local/files/uploads/7_Divers_01.pdf">7. Divers</a></p>','image' => 'files/pictos/bail/questions.jpg','url' => '','style' => '','rang' => '0','page_id' => '8','categorie_id' => NULL,'type' => 'autorite','created_at' => '2017-02-06 14:32:49','updated_at' => '2017-02-06 14:32:49','deleted_at' => NULL)
        );


        \DB::table('contents')->insert($contents);

    }
}