<?php

class ProfessionsTableSeeder extends \Illuminate\Database\Seeder  {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		DB::table('professions')->truncate();

		$professions = array(
			array('id' => '1','title' => 'Avocat'),
			array('id' => '2','title' => 'Juriste'),
			array('id' => '3','title' => 'Greffier'),
			array('id' => '4','title' => 'Assistant'),
			array('id' => '5','title' => 'Avocat-stagiaire'),
			array('id' => '6','title' => 'Chargé d’enseignement'),
			array('id' => '7','title' => 'Etudiant'),
			array('id' => '8','title' => 'Juge'),
			array('id' => '9','title' => 'Magistrat'),
			array('id' => '10','title' => 'Notaire'),
			array('id' => '11','title' => 'Notaire-stagiaire'),
			array('id' => '12','title' => 'Préposé cantonal'),
			array('id' => '13','title' => 'Procureur'),
			array('id' => '14','title' => 'Professeur'),
			array('id' => '15','title' => 'Stagiaire '),
			array('id' => '16','title' => 'Autre'),
			array('id' => '18','title' => 'Doctorant'),
			array('id' => '19','title' => 'Intervenant'),
			array('id' => '20','title' => 'Aide-assistant'),
			array('id' => '21','title' => 'Aide-secrétariat'),
			array('id' => '28','title' => 'Assistant-doctorant'),
			array('id' => '27','title' => 'Avocat-Notaire'),
			array('id' => '29','title' => 'Doctorant Unine'),
			array('id' => '30','title' => 'Assistant-social'),
			array('id' => '31','title' => 'Architecte'),
			array('id' => '32','title' => 'Ingénieur civil'),
			array('id' => '33','title' => 'Ingénieur géomètre'),
			array('id' => '34','title' => 'Ingénieur en techniques du bâtiment'),
			array('id' => '35','title' => 'Ingénieur'),
			array('id' => '36','title' => 'Informaticien'),
			array('id' => '37','title' => 'Ingénieur forestier'),
			array('id' => '38','title' => 'Ingénieur en génie rural'),
			array('id' => '39','title' => 'Ingénieur géologue'),
			array('id' => '40','title' => 'Président de commune ou syndic'),
			array('id' => '41','title' => 'Conservateur'),
			array('id' => '42','title' => 'Directeur du service de l\'urbanisme'),
			array('id' => '43','title' => 'Ingénieur mécanicien'),
			array('id' => '44','title' => 'Biologiste'),
			array('id' => '45','title' => 'Physicien'),
			array('id' => '46','title' => 'Ingénieur en sciences des matériaux'),
			array('id' => '47','title' => 'Ingénieur électricien'),
			array('id' => '48','title' => 'Géologue'),
			array('id' => '49','title' => 'Ingénieur en systèmes énergétiques'),
			array('id' => '50','title' => 'Hydrogéologue'),
			array('id' => '51','title' => 'Ingénieur chimiste'),
			array('id' => '52','title' => 'Ingénieur horloger'),
			array('id' => '53','title' => 'Aménagiste'),
			array('id' => '54','title' => 'Préfet'),
			array('id' => '55','title' => 'Gérant d’immeubles'),
			array('id' => '56','title' => 'Professeur honoraire'),
			array('id' => '57','title' => 'Tribunal'),
			array('id' => '58','title' => 'Médecin'),
			array('id' => '59','title' => 'Directeur administratif'),
			array('id' => '60','title' => 'Secrétaire général'),
			array('id' => '61','title' => 'Médecin cantonal'),
			array('id' => '62','title' => 'Dentiste'),
			array('id' => '63','title' => 'Docteur en droit'),
			array('id' => '64','title' => 'Economiste'),
			array('id' => '65','title' => 'Conseiller/ère juridique'),
			array('id' => '66','title' => 'Directeur/trice médical/e'),
			array('id' => '102','title' => 'Agent immobilier'),
			array('id' => '101','title' => 'Agent d\'affaires'),
			array('id' => '100','title' => 'Administrateur'),
			array('id' => '71','title' => 'Médiateur'),
			array('id' => '72','title' => 'Directeur/trice'),
			array('id' => '73','title' => 'Adjoint/e de direction'),
			array('id' => '74','title' => 'Ethicien'),
			array('id' => '75','title' => 'Secrétaire patronal'),
			array('id' => '76','title' => 'Responsable'),
			array('id' => '77','title' => 'Neuropsychologue'),
			array('id' => '78','title' => 'Responsable RH'),
			array('id' => '79','title' => 'Assistant/e de direction'),
			array('id' => '80','title' => 'Psychologue'),
			array('id' => '81','title' => 'Anesthésiste'),
			array('id' => '82','title' => 'Radiologue'),
			array('id' => '83','title' => 'Pharmacien-ne'),
			array('id' => '89','title' => 'Enseignant'),
			array('id' => '99','title' => 'Conseiller national'),
			array('id' => '87','title' => 'Chargée des relations extérieures et de la coopération'),
			array('id' => '97','title' => 'Urbaniste'),
			array('id' => '91','title' => 'Assureur'),
			array('id' => '92','title' => 'Conseiller financier'),
			array('id' => '93','title' => 'Conseiller fiscal'),
			array('id' => '94','title' => 'Journaliste'),
			array('id' => '95','title' => 'Policier'),
			array('id' => '96','title' => 'Collaborateur scientifique'),
			array('id' => '103','title' => 'Agent fiduciaire'),
			array('id' => '104','title' => 'Assesseur'),
			array('id' => '105','title' => 'Comptable'),
			array('id' => '106','title' => 'Collaborateur administratif'),
			array('id' => '107','title' => 'Régisseur'),
			array('id' => '108','title' => 'Gérant'),
			array('id' => '109','title' => 'Fondé de pouvoir'),
			array('id' => '110','title' => 'Employé de commerce'),
			array('id' => '111','title' => 'Courtier'),
			array('id' => '112','title' => 'Consultant'),
			array('id' => '113','title' => 'Directeur / Directeur adjoint'),
			array('id' => '114','title' => 'Infirmier/ère'),
			array('id' => '116','title' => 'Fiscaliste'),
			array('id' => '117','title' => 'Expert en immobilier')
		);
		
		// Uncomment the below to run the seeder
		DB::table('professions')->insert($professions);
	}

}
