<?php

class AuthorTableSeeder extends \Illuminate\Database\Seeder  {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		DB::table('authors')->truncate();

		$authors = array(
			array('id' => '1','first_name' => 'François','last_name' => 'Bohnet','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '2','first_name' => 'Pierre','last_name' => 'Wessner','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '3','first_name' => '','last_name' => 'La boîte','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '4','first_name' => 'Marino','last_name' => 'Montini','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '5','first_name' => 'Christoph','last_name' => 'Müller','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '6','first_name' => 'Antonio','last_name' => 'Rigozzi','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '7','first_name' => 'Ch.','last_name' => 'Guy-Ecabert','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '8','first_name' => 'Yvan','last_name' => 'Jeanneret','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '9','first_name' => 'André','last_name' => 'Kuhn','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '10','first_name' => 'Olivier','last_name' => 'Guillod','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '11','first_name' => 'Beatrice','last_name' => 'Stirner','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '12','first_name' => 'Dominique','last_name' => 'Sprumont','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '13','first_name' => 'Pascal','last_name' => 'Mahon','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '14','first_name' => 'Florence','last_name' => 'Guillaume','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '15','first_name' => 'Piermarco','last_name' => 'Zen-Ruffinen','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '16','first_name' => 'Christian','last_name' => 'Flueckiger','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '17','first_name' => 'Pierre-Emmanuel','last_name' => 'Ruedin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '18','first_name' => 'Laurent','last_name' => 'Bieri','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '19','first_name' => 'Jean-Luc','last_name' => 'Niklaus','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '20','first_name' => 'Olivier','last_name' => 'Chappuis','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '21','first_name' => 'Ursula','last_name' => 'Elsener','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '22','first_name' => 'Nour Ahmad','last_name' => 'Nazim','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '23','first_name' => 'Bernhard','last_name' => 'Pulver','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '24','first_name' => 'Nicholas','last_name' => 'Turin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '25','first_name' => 'Sibilla Giselda','last_name' => 'Cretti','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '26','first_name' => 'Mélanie','last_name' => 'Mader','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '27','first_name' => 'Sylvain','last_name' => 'Métille','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '28','first_name' => 'Jessica','last_name' => 'Salom','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '29','first_name' => 'Patricia','last_name' => 'Dietschy','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '30','first_name' => 'Olivier','last_name' => 'Gonin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '31','first_name' => 'Olivier','last_name' => 'Hari','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '32','first_name' => 'Daniel de Vries','last_name' => 'Reilingh','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '33','first_name' => 'Marie','last_name' => 'Deveaud-Plédran','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '34','first_name' => 'Sabrina','last_name' => 'Burgat','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '35','first_name' => 'Vincent','last_name' => 'Corpataux','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '36','first_name' => 'Brigitte','last_name' => 'Fasel','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '37','first_name' => 'Alexandre','last_name' => 'Papaux','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '38','first_name' => 'Béatrice','last_name' => 'Despland','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '39','first_name' => 'Thierry','last_name' => 'Obrist','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '40','first_name' => 'Alison','last_name' => 'Carty','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '41','first_name' => 'Estelle Mathis','last_name' => 'Zwygart','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '42','first_name' => 'Fanny','last_name' => 'Matthey','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '43','first_name' => 'Sylvain-Georges','last_name' => 'Kablan','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '44','first_name' => '','last_name' => 'P. Zen-Ruffinen (édit.)','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '45','first_name' => '','last_name' => 'Bohnet-Wessner (édit.)','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '46','first_name' => '','last_name' => 'Zen-Ruffinen/Auer (édit.)','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '47','first_name' => '','last_name' => 'Guillod-Müller (édit.)','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '48','first_name' => '','last_name' => 'Mahon-Nguyen (édit.)','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '49','first_name' => 'Nathalie','last_name' => 'Tissot','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '50','first_name' => 'Minh Son','last_name' => 'Nguyen','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '51','first_name' => 'Cesla','last_name' => 'Amarelle','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '52','first_name' => 'Denis','last_name' => 'Oswald','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '53','first_name' => 'Robert J.','last_name' => 'Danon','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '54','first_name' => 'Anne','last_name' => 'Benoit','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '55','first_name' => 'Christoph','last_name' => 'Mueller','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '56','first_name' => 'Jean-Philippe','last_name' => 'Dunand','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '58','first_name' => 'Alain','last_name' => 'Thévenaz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '59','first_name' => 'Nicolas','last_name' => 'Rouiller','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '60','first_name' => 'Vincent','last_name' => 'Martenet','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '61','first_name' => 'Lorraine','last_name' => 'Ducommun','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '62','first_name' => 'Eloi','last_name' => 'Jeannerat','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '63','first_name' => 'Dieyla','last_name' => 'Sow','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '64','first_name' => 'Camille','last_name' => 'Dubois','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '65','first_name' => 'Guy','last_name' => 'Longchamp','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '66','first_name' => 'Lino','last_name' => 'Hänni','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '67','first_name' => 'Nathalie','last_name' => 'Christen','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '68','first_name' => 'Anne-Sylvie','last_name' => 'Dupont','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '69','first_name' => 'Fanny','last_name' => 'Kunz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '70','first_name' => 'Valérie','last_name' => 'Maurer','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '71','first_name' => 'Laura','last_name' => 'Amey','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '72','first_name' => 'Rachel','last_name' => 'Christinat','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '73','first_name' => 'Alice','last_name' => 'Fadda','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '74','first_name' => 'Nadia','last_name' => 'Pascale','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '75','first_name' => 'Manon','last_name' => 'Fellrath','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '76','first_name' => 'Blaise','last_name' => 'Carron','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '77','first_name' => 'Alejandro','last_name' => 'Follonier-Ayala','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '78','first_name' => 'Olivier','last_name' => 'Riske','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '79','first_name' => 'Zachary','last_name' => 'Douglas','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '80','first_name' => 'Philipp','last_name' => 'Habegger','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '81','first_name' => 'Ulrich','last_name' => 'Haas','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '82','first_name' => 'Christoph','last_name' => 'Hurni','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '83','first_name' => 'Melissa','last_name' => 'Magliana','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '84','first_name' => 'Mike','last_name' => 'Morgan','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '85','first_name' => 'Yann','last_name' => 'Hafner','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '86','first_name' => 'Evelyne','last_name' => 'Clerc','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '87','first_name' => 'Yann','last_name' => 'Férolles','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '88','first_name' => 'Roxane','last_name' => 'Schaller','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '89','first_name' => 'Nicolas','last_name' => 'Brügger','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '90','first_name' => 'Julien','last_name' => 'Dubois','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '91','first_name' => 'Vincent','last_name' => 'Salvadé','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '92','first_name' => 'Valérie','last_name' => 'Wyssbrod','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '93','first_name' => 'Leila','last_name' => 'Ghassemi','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '94','first_name' => 'Daniel','last_name' => 'Kraus','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '95','first_name' => 'Gaétan','last_name' => 'Droz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '96','first_name' => 'Nicolas','last_name' => 'Pellaton','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '97','first_name' => 'Valentin','last_name' => 'Rétornaz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '98','first_name' => 'Erika','last_name' => 'Hasler','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '99','first_name' => 'Marlène','last_name' => 'Collette','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '100','first_name' => 'Yvan','last_name' => 'Fauchère','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '101','first_name' => 'Stefanie Tamara','last_name' => 'Kurt','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '102','first_name' => 'Natassia','last_name' => 'Martinez','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '103','first_name' => 'Alain','last_name' => 'Barbezat','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '104','first_name' => 'Agnès','last_name' => 'Hertig-Pea','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '105','first_name' => 'Aurélie','last_name' => 'Planas','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '106','first_name' => 'Manon','last_name' => 'Simeoni','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '107','first_name' => 'Estelle','last_name' => 'Mathis-Zwygart','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '108','first_name' => 'Jean-Luc','last_name' => 'Chenaux','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '109','first_name' => 'Ludivine','last_name' => 'Ferreira','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '110','first_name' => 'Bastien','last_name' => 'Durel','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '111','first_name' => 'Mari','last_name' => 'Viro Moser','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '112','first_name' => 'Joëlle','last_name' => 'Racine','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '113','first_name' => 'Nicolas','last_name' => 'Bueno','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '114','first_name' => 'Fanny','last_name' => 'Brossard','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '115','first_name' => 'Laurie','last_name' => 'Roth','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '116','first_name' => 'Daniel','last_name' => 'de Vries Reilingh','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '117','first_name' => 'Vincent','last_name' => 'Mignon','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '118','first_name' => 'Pascal','last_name' => 'Mahon','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '119','first_name' => 'Jean-Philippe','last_name' => 'Dunand','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '120','first_name' => 'Céline','last_name' => 'Tritten Helbling','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '121','first_name' => 'Theodor','last_name' => 'Bühler','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '122','first_name' => 'Sylvain','last_name' => 'Marchand','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '123','first_name' => 'Tobias','last_name' => 'Zuberbühler','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '124','first_name' => 'Luc','last_name' => 'Gonin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '125','first_name' => 'Sophie','last_name' => 'Weerts','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '126','first_name' => 'Alain','last_name' => 'Chablais','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '127','first_name' => 'Josiane','last_name' => 'Grand','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '128','first_name' => 'Bénédicte','last_name' => 'Pessotto','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '129','first_name' => 'Charlotte','last_name' => 'Rossat','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '130','first_name' => 'Leslie','last_name' => 'La Sala','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '131','first_name' => 'Raphaël','last_name' => 'Allimann','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '132','first_name' => 'Stéphane','last_name' => 'Brumann','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '133','first_name' => 'Leonor','last_name' => 'Acker-Hernández','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '134','first_name' => 'Héloïse','last_name' => 'Rosello','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '135','first_name' => 'Yasemin','last_name' => 'Hazinedar','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '136','first_name' => 'M.','last_name' => 'Tissot','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '137','first_name' => 'Micael','last_name' => 'Totaro','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '138','first_name' => 'Melanie','last_name' => 'van Leeuwen','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '139','first_name' => 'Jan','last_name' => 'Heiner Nedden','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '140','first_name' => 'Friedrich','last_name' => 'Rosenfeld','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '141','first_name' => 'Daniele','last_name' => 'Favalli','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '142','first_name' => 'Roxane','last_name' => 'Schmidgall','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '143','first_name' => 'Bernd','last_name' => 'Ehle','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '144','first_name' => 'Vanessa','last_name' => 'Alarcón Duvanel','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '145','first_name' => 'David P.','last_name' => 'Roney','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '146','first_name' => 'Katherine','last_name' => 'von der Weid','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '147','first_name' => 'Philippe','last_name' => 'Conod','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '148','first_name' => 'Philippe','last_name' => 'Conod','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '149','first_name' => 'Daniela','last_name' => 'Cerqui','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '150','first_name' => 'Carole','last_name' => 'Aubert','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '151','first_name' => 'Bertil','last_name' => 'Cottier','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '152','first_name' => 'Sébastien','last_name' => 'Fanti','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '153','first_name' => 'Geneviève','last_name' => 'Ordolli','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '154','first_name' => 'Régine','last_name' => 'Delley','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '155','first_name' => 'Olivier','last_name' => 'Subilia','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '156','first_name' => 'Niklaus','last_name' => 'Meier','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '157','first_name' => 'Anaïc','last_name' => 'Cordoba','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '158','first_name' => 'Steve','last_name' => 'Reusser','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '159','first_name' => 'Christian','last_name' => 'Crocetta','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '160','first_name' => 'Guillaume','last_name' => 'Jéquier','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '161','first_name' => 'Lino','last_name' => 'Hänni','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '162','first_name' => 'Valérie','last_name' => 'Défago Gaudin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '163','first_name' => 'Tifenn','last_name' => 'Beuret','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '164','first_name' => 'Andrina','last_name' => 'Cavelti','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '165','first_name' => 'Rabia','last_name' => 'Amor','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '166','first_name' => 'Ulysse','last_name' => 'DuPasquier','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '167','first_name' => 'Julien','last_name' => 'Delaye','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '168','first_name' => 'Jonathan','last_name' => 'Gretillat','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '169','first_name' => 'Charlotte','last_name' => 'Boulay','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '170','first_name' => 'Frédéric','last_name' => 'Erard','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '171','first_name' => 'Leticia','last_name' => 'Boni','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '172','first_name' => 'Alain','last_name' => 'Bauer','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '173','first_name' => 'Philippe','last_name' => 'Meier','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '174','first_name' => 'Noémie','last_name' => 'Helle','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '175','first_name' => 'Audrey','last_name' => 'Leuba','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '176','first_name' => 'Luc','last_name' => 'Pittet','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '177','first_name' => 'Julien','last_name' => 'Broquet','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '178','first_name' => 'François','last_name' => 'Chaix','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '179','first_name' => 'Jacques','last_name' => 'Haldy','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '180','first_name' => 'Nicolas','last_name' => 'Jeandin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '181','first_name' => 'Samuel','last_name' => 'Monbaron','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '182','first_name' => 'Denis','last_name' => 'Piotet','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '183','first_name' => 'Bastien','last_name' => 'Sandoz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '184','first_name' => 'Denis','last_name' => 'Tappy','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '185','first_name' => 'Philippe','last_name' => 'Bauer','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '186','first_name' => 'Nicolas','last_name' => 'Feuz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '187','first_name' => 'Robert','last_name' => 'Roth','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '188','first_name' => 'Alexandre','last_name' => 'Seiler','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '189','first_name' => 'Niels','last_name' => 'Sörensen','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '190','first_name' => 'Martine','last_name' => 'Dang','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '191','first_name' => 'Véronique','last_name' => 'Boillet','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '192','first_name' => 'Matthieu','last_name' => 'Corbaz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '193','first_name' => 'Roswitha','last_name' => 'Petry','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '194','first_name' => 'Sébastien','last_name' => 'Besson','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '195','first_name' => 'Olivier','last_name' => 'Caprasse','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '196','first_name' => 'Maarten','last_name' => 'Draye','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '197','first_name' => 'Ignacio','last_name' => 'de Castro','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '198','first_name' => 'Félix','last_name' => 'Dasser','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '199','first_name' => 'Anne-Véronique','last_name' => 'Schlaepfer','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '200','first_name' => 'Fabrice','last_name' => 'Robert-Tissot','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '201','first_name' => 'Francesco','last_name' => 'Trezzini','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '202','first_name' => 'Etienne','last_name' => 'Henry','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '203','first_name' => 'Baptiste','last_name' => 'Viredaz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '204','first_name' => 'Sylvie','last_name' => 'Wegelin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '205','first_name' => 'Pierre','last_name' => 'Aubert','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '206','first_name' => 'Placidus','last_name' => 'Plattner','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '207','first_name' => 'Pascal','last_name' => 'Pichonnaz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '208','first_name' => 'David','last_name' => 'Lachat','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '209','first_name' => 'Muriel','last_name' => 'Barrelet','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '210','first_name' => 'Pascal','last_name' => 'Terrapon','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '211','first_name' => 'Karin','last_name' => 'Grobet Thorens','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '212','first_name' => 'Andrea','last_name' => 'Braconi','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '213','first_name' => 'Michel','last_name' => 'Rossinelli','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '214','first_name' => 'Gianmaria','last_name' => 'Mosca','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '215','first_name' => 'Jean-Jacques','last_name' => 'Schwaab','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '216','first_name' => 'Thomas','last_name' => 'Probst','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '217','first_name' => 'Jean-Marc','last_name' => 'Siegrist','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '218','first_name' => 'Philippe','last_name' => 'Béguin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '219','first_name' => 'Ariane','last_name' => 'Morin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '220','first_name' => 'Bertrand','last_name' => 'Reeb','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '221','first_name' => 'Daniel','last_name' => 'Devaud','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '222','first_name' => 'Michel','last_name' => 'Ducrot','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '223','first_name' => 'Vincent','last_name' => 'Brulhart','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '224','first_name' => 'François','last_name' => 'Knoepfler','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '225','first_name' => 'Pierre-Emmanuel','last_name' => 'Ruedin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '226','first_name' => 'Jacques','last_name' => 'Micheli','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '227','first_name' => 'Fabienne','last_name' => 'Byrde','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '228','first_name' => 'Marie-Gisèle','last_name' => 'Danthe','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '229','first_name' => 'Hélène','last_name' => 'Ecoutin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '230','first_name' => 'Nicole','last_name' => 'Golay','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '231','first_name' => 'Karine','last_name' => 'Lempen','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '232','first_name' => 'Franciska','last_name' => 'Krings','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '233','first_name' => 'Rebekka','last_name' => 'Steiner','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '234','first_name' => 'Sandrine','last_name' => 'Tornare','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '235','first_name' => 'Norma','last_name' => 'Streit-Luzio','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '236','first_name' => 'Luc','last_name' => 'Wenger','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '237','first_name' => 'Markus','last_name' => 'Müller-Chen','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '238','first_name' => 'Corinne','last_name' => 'Widmer Lüchinger','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '239','first_name' => 'Patrick','last_name' => 'Brozzo','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '240','first_name' => 'Sandra','last_name' => 'Hotz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '241','first_name' => 'Eveline','last_name' => 'Schneider Kayasseh','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '242','first_name' => 'Sylvain','last_name' => 'Félix','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '243','first_name' => 'Adrien','last_name' => 'Wyssbrod','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '244','first_name' => 'Madalina','last_name' => 'Diaconu','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '245','first_name' => 'Elisabeth','last_name' => 'Volckrick','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '246','first_name' => 'Rahel','last_name' => 'Diethelm','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '247','first_name' => 'Semsija','last_name' => 'Etemi','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '248','first_name' => 'Céline','last_name' => 'Gutzwiller','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '249','first_name' => 'Amédéo','last_name' => 'Wermelinger','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '250','first_name' => 'Jacques','last_name' => 'Ansermet','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '251','first_name' => 'Nicolas','last_name' => 'Saviaux','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '252','first_name' => 'Maryse','last_name' => 'Pradervand-Kernen','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '253','first_name' => 'Michel','last_name' => 'Mooser','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '254','first_name' => 'Nicolas','last_name' => 'Jeandin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '255','first_name' => 'Alen','last_name' => 'Udovcic','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '256','first_name' => 'Didier','last_name' => 'Leyvraz','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '257','first_name' => 'Delphine','last_name' => 'Yerly','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '258','first_name' => 'Marine','last_name' => 'Oppliger','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '259','first_name' => 'Christelle','last_name' => 'Froidevaux','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '260','first_name' => 'Quentin','last_name' => 'Herold','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '261','first_name' => 'Lucien','last_name' => 'Colliander','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '262','first_name' => 'Nahal','last_name' => 'Aminian','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '263','first_name' => 'Pascal','last_name' => 'Jeannin','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '264','first_name' => 'Aurelia','last_name' => 'Sculati','occupation' => '','bio' => '','photo' => '','rang' => NULL),
			array('id' => '266','first_name' => 'Simon','last_name' => 'Othenin-Girard','occupation' => '','bio' => NULL,'photo' => NULL,'rang' => NULL),
			array('id' => '267','first_name' => 'Carole','last_name' => 'Sonnenberg','occupation' => '','bio' => NULL,'photo' => NULL,'rang' => NULL),
			array('id' => '268','first_name' => 'Tania','last_name' => 'Ferreira','occupation' => '','bio' => NULL,'photo' => NULL,'rang' => NULL),
			array('id' => '269','first_name' => 'Olivier','last_name' => 'Bleicker','occupation' => '','bio' => NULL,'photo' => NULL,'rang' => NULL),
			array('id' => '270','first_name' => 'Alexandre','last_name' => 'Massard','occupation' => '','bio' => NULL,'photo' => NULL,'rang' => NULL),
			array('id' => '272','first_name' => 'Patricia','last_name' => 'Dietschy-Martenet','occupation' => '','bio' => NULL,'photo' => NULL,'rang' => NULL),
			array('id' => '273','first_name' => 'Sabrina','last_name' => 'Burgat,','occupation' => '','bio' => NULL,'photo' => NULL,'rang' => NULL),
			array('id' => '274','first_name' => 'Cindy','last_name' => 'Leschaud','occupation' => 'Déveloopeur web @ UniNE','bio' => '<p>Quis consectetur aenean dictumst proîn ïd prétium namé mattisé nullä aptenuscipit est nullä, anonyma eget scelerisque class aenanm mié àc ornare fermentum cél leçtus vivérra séd.</p>','photo' => 'cindy_mini.jpg','rang' => '0')
		);

		// Uncomment the below to run the seeder
		DB::table('authors')->insert($authors);
	}

}
