<?php

class PaysTableSeeder extends \Illuminate\Database\Seeder  {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		DB::table('pays')->truncate();

		$pays = array(
			  array('code' => 'AF','title' => 'Afghanistan'),
			  array('code' => 'ZA','title' => 'Afrique du Sud'),
			  array('code' => 'AL','title' => 'Albanie'),
			  array('code' => 'DZ','title' => 'Algérie'),
			  array('code' => 'DE','title' => 'Allemagne'),
			  array('code' => 'AD','title' => 'Andorre'),
			  array('code' => 'AO','title' => 'Angola'),
			  array('code' => 'AI','title' => 'Anguilla'),
			  array('code' => 'AQ','title' => 'Antarctique'),
			  array('code' => 'AG','title' => 'Antigua-et-Barbuda'),
			  array('code' => 'AN','title' => 'Antilles néerlandaises'),
			  array('code' => 'SA','title' => 'Arabie saoudite'),
			  array('code' => 'AR','title' => 'Argentine'),
			  array('code' => 'AM','title' => 'Arménie'),
			  array('code' => 'AW','title' => 'Aruba'),
			  array('code' => 'AU','title' => 'Australie'),
			  array('code' => 'AT','title' => 'Autriche'),
			  array('code' => 'AZ','title' => 'Azerbaïdjan'),
			  array('code' => 'BJ','title' => 'Bénin'),
			  array('code' => 'BS','title' => 'Bahamas'),
			  array('code' => 'BH','title' => 'Bahreïn'),
			  array('code' => 'BD','title' => 'Bangladesh'),
			  array('code' => 'BB','title' => 'Barbade'),
			  array('code' => 'PW','title' => 'Belau'),
			  array('code' => 'BE','title' => 'Belgique'),
			  array('code' => 'BZ','title' => 'Belize'),
			  array('code' => 'BM','title' => 'Bermudes'),
			  array('code' => 'BT','title' => 'Bhoutan'),
			  array('code' => 'BY','title' => 'Biélorussie'),
			  array('code' => 'MM','title' => 'Birmanie'),
			  array('code' => 'BO','title' => 'Bolivie'),
			  array('code' => 'BA','title' => 'Bosnie-Herzégovine'),
			  array('code' => 'BW','title' => 'Botswana'),
			  array('code' => 'BR','title' => 'Brésil'),
			  array('code' => 'BN','title' => 'Brunei'),
			  array('code' => 'BG','title' => 'Bulgarie'),
			  array('code' => 'BF','title' => 'Burkina Faso'),
			  array('code' => 'BI','title' => 'Burundi'),
			  array('code' => 'CI','title' => 'Côte d\'Ivoire'),
			  array('code' => 'KH','title' => 'Cambodge'),
			  array('code' => 'CM','title' => 'Cameroun'),
			  array('code' => 'CA','title' => 'Canada'),
			  array('code' => 'CV','title' => 'Cap-Vert'),
			  array('code' => 'CL','title' => 'Chili'),
			  array('code' => 'CN','title' => 'Chine'),
			  array('code' => 'CY','title' => 'Chypre'),
			  array('code' => 'CO','title' => 'Colombie'),
			  array('code' => 'KM','title' => 'Comores'),
			  array('code' => 'CG','title' => 'Congo'),
			  array('code' => 'KP','title' => 'Corée du Nord'),
			  array('code' => 'KR','title' => 'Corée du Sud'),
			  array('code' => 'CR','title' => 'Costa Rica'),
			  array('code' => 'HR','title' => 'Croatie'),
			  array('code' => 'CU','title' => 'Cuba'),
			  array('code' => 'DK','title' => 'Danemark'),
			  array('code' => 'DJ','title' => 'Djibouti'),
			  array('code' => 'DM','title' => 'Dominique'),
			  array('code' => 'EG','title' => 'Égypte'),
			  array('code' => 'AE','title' => 'Émirats arabes unis'),
			  array('code' => 'EC','title' => 'Équateur'),
			  array('code' => 'ER','title' => 'Érythrée'),
			  array('code' => 'ES','title' => 'Espagne'),
			  array('code' => 'EE','title' => 'Estonie'),
			  array('code' => 'US','title' => 'États-Unis'),
			  array('code' => 'ET','title' => 'Éthiopie'),
			  array('code' => 'FI','title' => 'Finlande'),
			  array('code' => 'FR','title' => 'France'),
			  array('code' => 'GE','title' => 'Géorgie'),
			  array('code' => 'GA','title' => 'Gabon'),
			  array('code' => 'GM','title' => 'Gambie'),
			  array('code' => 'GH','title' => 'Ghana'),
			  array('code' => 'GI','title' => 'Gibraltar'),
			  array('code' => 'GR','title' => 'Grèce'),
			  array('code' => 'GD','title' => 'Grenade'),
			  array('code' => 'GL','title' => 'Groenland'),
			  array('code' => 'GP','title' => 'Guadeloupe'),
			  array('code' => 'GU','title' => 'Guam'),
			  array('code' => 'GT','title' => 'Guatemala'),
			  array('code' => 'GN','title' => 'Guinée'),
			  array('code' => 'GQ','title' => 'Guinée équatoriale'),
			  array('code' => 'GW','title' => 'Guinée-Bissao'),
			  array('code' => 'GY','title' => 'Guyana'),
			  array('code' => 'GF','title' => 'Guyane française'),
			  array('code' => 'HT','title' => 'Haïti'),
			  array('code' => 'HN','title' => 'Honduras'),
			  array('code' => 'HK','title' => 'Hong Kong'),
			  array('code' => 'HU','title' => 'Hongrie'),
			  array('code' => 'BV','title' => 'Ile Bouvet'),
			  array('code' => 'CX','title' => 'Ile Christmas'),
			  array('code' => 'NF','title' => 'Ile Norfolk'),
			  array('code' => 'KY','title' => 'Iles Cayman'),
			  array('code' => 'CK','title' => 'Iles Cook'),
			  array('code' => 'FO','title' => 'Iles Féroé'),
			  array('code' => 'FK','title' => 'Iles Falkland'),
			  array('code' => 'FJ','title' => 'Iles Fidji'),
			  array('code' => 'GS','title' => 'Iles Géorgie du Sud et Sandwich du Sud'),
			  array('code' => 'HM','title' => 'Iles Heard et McDonald'),
			  array('code' => 'MH','title' => 'Iles Marshall'),
			  array('code' => 'PN','title' => 'Iles Pitcairn'),
			  array('code' => 'SB','title' => 'Iles Salomon'),
			  array('code' => 'SJ','title' => 'Iles Svalbard et Jan Mayen'),
			  array('code' => 'TC','title' => 'Iles Turks-et-Caicos'),
			  array('code' => 'VI','title' => 'Iles Vierges américaines'),
			  array('code' => 'VG','title' => 'Iles Vierges britanniques'),
			  array('code' => 'CC','title' => 'Iles des Cocos (Keeling)'),
			  array('code' => 'UM','title' => 'Iles mineures éloignées des États-Unis'),
			  array('code' => 'IN','title' => 'Inde'),
			  array('code' => 'ID','title' => 'Indonésie'),
			  array('code' => 'IR','title' => 'Iran'),
			  array('code' => 'IQ','title' => 'Iraq'),
			  array('code' => 'IE','title' => 'Irlande'),
			  array('code' => 'IS','title' => 'Islande'),
			  array('code' => 'IL','title' => 'Israël'),
			  array('code' => 'IT','title' => 'Italie'),
			  array('code' => 'JM','title' => 'Jamaïque'),
			  array('code' => 'JP','title' => 'Japon'),
			  array('code' => 'JO','title' => 'Jordanie'),
			  array('code' => 'KZ','title' => 'Kazakhstan'),
			  array('code' => 'KE','title' => 'Kenya'),
			  array('code' => 'KG','title' => 'Kirghizistan'),
			  array('code' => 'KI','title' => 'Kiribati'),
			  array('code' => 'KW','title' => 'Koweït'),
			  array('code' => 'LA','title' => 'Laos'),
			  array('code' => 'LS','title' => 'Lesotho'),
			  array('code' => 'LV','title' => 'Lettonie'),
			  array('code' => 'LB','title' => 'Liban'),
			  array('code' => 'LR','title' => 'Liberia'),
			  array('code' => 'LY','title' => 'Libye'),
			  array('code' => 'LI','title' => 'Liechtenstein'),
			  array('code' => 'LT','title' => 'Lituanie'),
			  array('code' => 'LU','title' => 'Luxembourg'),
			  array('code' => 'MO','title' => 'Macao'),
			  array('code' => 'MG','title' => 'Madagascar'),
			  array('code' => 'MY','title' => 'Malaisie'),
			  array('code' => 'MW','title' => 'Malawi'),
			  array('code' => 'MV','title' => 'Maldives'),
			  array('code' => 'ML','title' => 'Mali'),
			  array('code' => 'MT','title' => 'Malte'),
			  array('code' => 'MP','title' => 'Mariannes du Nord'),
			  array('code' => 'MA','title' => 'Maroc'),
			  array('code' => 'MQ','title' => 'Martinique'),
			  array('code' => 'MU','title' => 'Maurice'),
			  array('code' => 'MR','title' => 'Mauritanie'),
			  array('code' => 'YT','title' => 'Mayotte'),
			  array('code' => 'MX','title' => 'Mexique'),
			  array('code' => 'FM','title' => 'Micronésie'),
			  array('code' => 'MD','title' => 'Moldavie'),
			  array('code' => 'MC','title' => 'Monaco'),
			  array('code' => 'MN','title' => 'Mongolie'),
			  array('code' => 'MS','title' => 'Montserrat'),
			  array('code' => 'MZ','title' => 'Mozambique'),
			  array('code' => 'NP','title' => 'Népal'),
			  array('code' => 'NA','title' => 'Namibie'),
			  array('code' => 'NR','title' => 'Nauru'),
			  array('code' => 'NI','title' => 'Nicaragua'),
			  array('code' => 'NE','title' => 'Niger'),
			  array('code' => 'NG','title' => 'Nigeria'),
			  array('code' => 'NU','title' => 'Nioué'),
			  array('code' => 'NO','title' => 'Norvège'),
			  array('code' => 'NC','title' => 'Nouvelle-Calédonie'),
			  array('code' => 'NZ','title' => 'Nouvelle-Zélande'),
			  array('code' => 'OM','title' => 'Oman'),
			  array('code' => 'UG','title' => 'Ouganda'),
			  array('code' => 'UZ','title' => 'Ouzbékistan'),
			  array('code' => 'PE','title' => 'Pérou'),
			  array('code' => 'PK','title' => 'Pakistan'),
			  array('code' => 'PA','title' => 'Panama'),
			  array('code' => 'PG','title' => 'Papouasie-Nouvelle-Guinée'),
			  array('code' => 'PY','title' => 'Paraguay'),
			  array('code' => 'NL','title' => 'Pays-Bas'),
			  array('code' => 'PH','title' => 'Philippines'),
			  array('code' => 'PL','title' => 'Pologne'),
			  array('code' => 'PF','title' => 'Polynésie française'),
			  array('code' => 'PR','title' => 'Porto Rico'),
			  array('code' => 'PT','title' => 'Portugal'),
			  array('code' => 'QA','title' => 'Qatar'),
			  array('code' => 'CF','title' => 'République centrafricaine'),
			  array('code' => 'CD','title' => 'République démocratique du Congo'),
			  array('code' => 'DO','title' => 'République dominicaine'),
			  array('code' => 'CZ','title' => 'République tchèque'),
			  array('code' => 'RE','title' => 'Réunion'),
			  array('code' => 'RO','title' => 'Roumanie'),
			  array('code' => 'GB','title' => 'Royaume-Uni'),
			  array('code' => 'RU','title' => 'Russie'),
			  array('code' => 'RW','title' => 'Rwanda'),
			  array('code' => 'SN','title' => 'Sénégal'),
			  array('code' => 'EH','title' => 'Sahara occidental'),
			  array('code' => 'KN','title' => 'Saint-Christophe-et-Niévès'),
			  array('code' => 'SM','title' => 'Saint-Marin'),
			  array('code' => 'PM','title' => 'Saint-Pierre-et-Miquelon'),
			  array('code' => 'VA','title' => 'Saint-Siège '),
			  array('code' => 'VC','title' => 'Saint-Vincent-et-les-Grenadines'),
			  array('code' => 'SH','title' => 'Sainte-Hélène'),
			  array('code' => 'LC','title' => 'Sainte-Lucie'),
			  array('code' => 'SV','title' => 'Salvador'),
			  array('code' => 'WS','title' => 'Samoa'),
			  array('code' => 'AS','title' => 'Samoa américaines'),
			  array('code' => 'ST','title' => 'Sao Tomé-et-Principe'),
			  array('code' => 'SC','title' => 'Seychelles'),
			  array('code' => 'SL','title' => 'Sierra Leone'),
			  array('code' => 'SG','title' => 'Singapour'),
			  array('code' => 'SI','title' => 'Slovénie'),
			  array('code' => 'SK','title' => 'Slovaquie'),
			  array('code' => 'SO','title' => 'Somalie'),
			  array('code' => 'SD','title' => 'Soudan'),
			  array('code' => 'LK','title' => 'Sri Lanka'),
			  array('code' => 'SE','title' => 'Suède'),
			  array('code' => 'CH','title' => 'Suisse'),
			  array('code' => 'SR','title' => 'Suriname'),
			  array('code' => 'SZ','title' => 'Swaziland'),
			  array('code' => 'SY','title' => 'Syrie'),
			  array('code' => 'TW','title' => 'Taïwan'),
			  array('code' => 'TJ','title' => 'Tadjikistan'),
			  array('code' => 'TZ','title' => 'Tanzanie'),
			  array('code' => 'TD','title' => 'Tchad'),
			  array('code' => 'TF','title' => 'Terres australes françaises'),
			  array('code' => 'IO','title' => 'Territoire britannique de l\'Océan Indien'),
			  array('code' => 'TH','title' => 'Thaïlande'),
			  array('code' => 'TL','title' => 'Timor Oriental'),
			  array('code' => 'TG','title' => 'Togo'),
			  array('code' => 'TK','title' => 'Tokélaou'),
			  array('code' => 'TO','title' => 'Tonga'),
			  array('code' => 'TT','title' => 'Trinité-et-Tobago'),
			  array('code' => 'TN','title' => 'Tunisie'),
			  array('code' => 'TM','title' => 'Turkménistan'),
			  array('code' => 'TR','title' => 'Turquie'),
			  array('code' => 'TV','title' => 'Tuvalu'),
			  array('code' => 'UA','title' => 'Ukraine'),
			  array('code' => 'UY','title' => 'Uruguay'),
			  array('code' => 'VU','title' => 'Vanuatu'),
			  array('code' => 'VE','title' => 'Venezuela'),
			  array('code' => 'VN','title' => 'Viêtnam'),
			  array('code' => 'WF','title' => 'Wallis-et-Futuna'),
			  array('code' => 'YE','title' => 'Yémen'),
			  array('code' => 'YU','title' => 'Yougoslavie'),
			  array('code' => 'ZM','title' => 'Zambie'),
			  array('code' => 'ZW','title' => 'Zimbabwe'),
			  array('code' => 'MK','title' => 'ex-République yougoslave de Macédoine')
		);

		// Uncomment the below to run the seeder
		DB::table('pays')->insert($pays);
	}

}
